export const governorateOptions = [
  { value: "Ariana", label: "Ariana", cities: ["Ariana Ville", "Ettadhamen", "Kalaat Landlous", "Borj louzir", "La Soukra", "Mnihla", "Raoued", "Sidi Thabet", "Charguia", "El Menzah", "Les jardin d'el Manzeh", "Ennasr", "El Manar"] },
  { value: "Béja", label: "Béja", cities: ["Amdoun", "Béja", "Goubellat", "Mejez El Bab", "Nefza", "Teboursouk", "Testour", "Thibar"] },
  { value: "Ben Arous", label: "Ben Arous", cities: ["Ben Arous", "Bou Mhel El Bassatine", "El Mourouj", "Ezzahra", "Fouchana", "Hammam Chatt", "Hammam Lif", "Megrine", "Mohamadia", "Mornag", "Nouvelle Medina", "Rades", "El Kabbaria", "El Ouerdia", "Jebel Jelloud"] },
  { value: "Bizerte", label: "Bizerte", cities: ["Bizerte Nord", "Bizerte Sud", "El Alia", "Ghar El Melh", "Ghezala", "Jarzouna", "Joumine", "Mateur", "Menzel Bourguiba", "Menzel Jemil", "Ras Jebel", "Sejnane", "Tinja", "Utique"] },
  { value: "Gabès", label: "Gabès", cities: ["El Hamma", "El Metouia", "Gabes Medina", "Gabes Ouest", "Gabes Sud", "Ghannouche", "Mareth", "Matmata", "Menzel Habib", "Nouvelle Matmata"] },
  { value: "Gafsa", label: "Gafsa", cities: ["Belkhir", "El Guettar", "El Ksar", "El Mdhilla", "Gafsa Nord", "Gafsa Sud", "Metlaoui", "Moulares", "Redeyef", "Sidi Aich", "Sned"] },
  { value: "Jendouba", label: "Jendouba", cities: ["Ain Draham", "Balta Bou Aouene", "Bou Salem", "Fernana", "Ghardimaou", "Jendouba", "Oued Mliz", "Tabarka"] },
  { value: "Kairouan", label: "Kairouan", cities: ["Bou Hajla", "Chebika", "Cherarda", "El Ala", "Haffouz", "Hajeb El Ayoun", "Kairouan Nord", "Kairouan Sud", "Nasrallah", "Oueslatia", "Sbikha"] },
  { value: "Kasserine", label: "Kasserine", cities: ["El Ayoun", "Ezzouhour (Kasserine)", "Feriana", "Foussana", "Haidra", "Jediliane", "Kasserine Nord", "Kasserine Sud", "Mejel Bel Abbes", "Sbeitla", "Sbiba", "Thala"] },
  { value: "Kébili", label: "Kébili", cities: ["Douz", "El Faouar", "Kebili Nord", "Kebili Sud", "Souk El Ahad"] },
  { value: "Le Kef", label: "Le Kef", cities: ["Dahmani", "El Ksour", "Jerissa", "Kalaa El Khasba", "Kalaat Sinane", "Le Kef", "Le Sers", "Nebeur", "Sakiet Sidi Youssef", "Tajerouine", "Touiref"] },
  { value: "Mahdia", label: "Mahdia", cities: ["Bou Merdes", "Chorbane", "El Jem", "Hbira", "Ksour Essaf", "La Chebba", "Mahdia", "Melloulech", "Ouled Chamakh", "Sidi Alouene", "Souassi"] },
  { value: "La Manouba", label: "La Manouba", cities: ["Borj El Amri", "Douar Hicher", "El Battan", "Jedaida", "Mornaguia", "Oued Ellil", "Tebourba", "Mannouba"] },
  { value: "Médenine", label: "Médenine", cities: ["Ajim", "Ben Guerdane", "Beni Khedache", "Djerba - Houmet Essouk", "Djerba - Midoun", "Medenine Nord", "Medenine Sud", "Sidi Makhlouf", "Zarzis"] },
  { value: "Monastir", label: "Monastir", cities: ["Bekalta", "Bembla", "Beni Hassen", "Jemmal", "Ksar Helal", "Ksibet El Mediouni", "Moknine", "Monastir", "Ouerdanine", "Sahline", "Sayada Lamta Bou Hajar", "Teboulba", "Zeramdine"] },
  { value: "Nabeul", label: "Nabeul", cities: ["Beni Khalled", "Beni Khiar", "Bou Argoub", "Dar Chaabane Elfehri", "El Haouaria", "El Mida", "Grombalia", "Hammam El Ghezaz", "Hammamet", "Kelibia", "Korba", "Menzel Bouzelfa", "Menzel Temime", "Nabeul", "Soliman", "Takelsa"] },
  { value: "Sfax", label: "Sfax", cities: ["Centre Ville", "La ville de sfax", "Agareb", "Bir Ali Ben Khelifa", "El Amra", "El Hencha", "Esskhira", "Ghraiba", "Jebeniana", "Kerkenah", "Mahras", "Menzel Chaker"] },
  { value: "Sidi Bouzid", label: "Sidi Bouzid", cities: ["Ben Oun", "Bir El Haffey", "Cebbala", "Jilma", "Maknassy", "Menzel Bouzaiene", "Mezzouna", "Ouled Haffouz", "Regueb", "Sidi Bouzid Est", "Sidi Bouzid Ouest", "Souk Jedid"] },
  { value: "Siliana", label: "Siliana", cities: ["Bargou", "Bou Arada", "El Aroussa", "Gaafour", "Kesra", "Le Krib", "Makthar", "Rohia", "Sidi Bou Rouis", "Siliana"] },
  { value: "Sousse", label: "Sousse", cities: ["Akouda", "Bou Ficha", "Enfidha", "Hammam Sousse", "Hergla", "Kalaa El Kebira", "Kalaa Essghira", "Kondar", "Msaken", "Sidi Bou Ali", "Sidi El Heni", "Sousse Jaouhara", "Sousse Riadh", "Sousse Ville"] },
  { value: "Tataouine", label: "Tataouine", cities: ["Bir Lahmar", "Dhehiba", "Ghomrassen", "Remada", "Smar", "Tataouine Nord", "Tataouine Sud"] },
  { value: "Tozeur", label: "Tozeur", cities: ["Degueche", "Hezoua", "Nefta", "Tameghza", "Tozeur"] },
  { value: "Tunis", label: "Tunis", cities: ["Centre ville", "Bab Souika", "Bab SAADOUN", "Bab EL KHADRA", "Carthage", "Cité El Khadra", "El Hrairia", "El Kram", "El Omrane", "El Omrane Superieur", "Essijoumi", "Ettahrir", "Ezzouhour (Tunis)", "La Goulette", "La Marsa", "La Medina", "Le Bardo", "Sidi El Bechir", "Sidi Hassine", "Ain zaghouen", "Lac", "L'aouina", "Gammarth", "Cité el khadra"] },
  { value: "Zaghouan", label: "Zaghouan", cities: ["Bir Mcherga", "El Fahs", "Ennadhour", "Hammam Zriba", "Saouef", "Zaghouan"] },
];

